server:
  port: 0

spring:
  application:
    name: logs-service
  eureka:
    client:
      service-url:
        defaultZone: ${EUREKA_URL}
    instance:
      instance-id: ${spring.application.name}:${random.uuid}
  data:
    elasticsearch:
      cluster-nodes: ${SPRING_DATA_ELASTICSEARCH_CLUSTER_NODES}
      rest:
        read-timeout: 5000
        connection-timeout: 5000
        max-connections: 10
        max-connections-per-route: 5
        connection-request-timeout: 5000

logging:
  level:
    root: INFO
    com.example: DEBUG