server:
  port: 0

spring:
  application:
    name: logs-service
  eureka:
    client:
      service-url:
        defaultZone: ${EUREKA_URL}
    instance:
      instance-id: ${spring.application.name}:${random.uuid}

logging:
  pattern:
    level: '%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]'