server:
  port: 8082
spring:
  application:
    name: currency-client
  eureka:
    client:
      service-url:
        defaultZone: ${EUREKA_URL}
    instance:
      instance-id: ${spring.application.name}:${random.uuid}
  kafka:
    bootstrapServers: ${KAFKA_PORT}
  redis:
    host: redis
    port: 6379
    client-name: ${spring.application.name}
    client-type: lettuce #provide reactive connection
    date_format: "dd-MM-yyyy"
    time_format: "HH:mm:ss"