server:
  port: 0
spring:
  application:
    name: mail-sender
  eureka:
    client:
      service-url:
        defaultZone: ${EUREKA_URL}
    instance:
      instance-id: ${spring.application.name}:${random.uuid}
  kafka:
    consumer:
      bootstrapServers: kafka:9092
      auto-offset-reset: earliest
      group_id: message
      key-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      properties:
        spring.json.trusted.packages: '*'
        spring.json.use.type.headers: false
        spring.json.value.default.type: com.specific.group.mail.sender.dto.BaseMessage
        spring.deserializer.key.delegate.class: org.apache.kafka.common.serialization.StringDeserializer
        spring.deserializer.value.delegate.class: org.springframework.kafka.support.serializer.JsonDeserializer
    topics:
     message: message

  mail:
    host: "smtp.gmail.com"
    port: 587
    username: currency.converter.application@gmail.com
    password: bkke sjnd yrbp erfe
    properties:
      mail:
        smtp:
          starttls:
            enable: true
          auth: true
