server:
  port: 0
spring:
  application:
    name: mail-sender
  eureka:
    client:
      service-url:
        defaultZone: ${EUREKA_URL}
    instance:
      instance-id: ${spring.application.name}:${random.uuid}
  kafka:
    consumer:
      bootstrapServers: kafka:9092
      auto-offset-reset: earliest
      group_id: message
      key-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      properties:
        spring.json.trusted.packages: '*'
        spring.json.use.type.headers: false
        spring.json.value.default.type: com.specific.group.mail.sender.dto.BaseMessage
        spring.deserializer.key.delegate.class: org.apache.kafka.common.serialization.StringDeserializer
        spring.deserializer.value.delegate.class: org.springframework.kafka.support.serializer.JsonDeserializer
    topics:
     message: message

  mail:
    host: "smtp.gmail.com"
    port: 587
    username: "currency.converter.application@gmail.com"
    password: "{cipher}AQC8x7RLChhu6m34MUS8am+y2/2JnmFfgl2bPK9Me1IQQMu+oXpDUGYFUrbSlNP+5uY0/BLaLhe7yBrDpnCYKbWfO393+GoPfYzJZg7DQAtH7sX36fF31aJslD9vemjvJuEfLSpsxXa11v2pudS/BhXA6v8eYByzZXxT1Ycf2cmTBW6mOoCq4oLANSBcRiWwAsaULhgT/W1O679yH6ApdFCqkwCUT0eQ5WDr08VirUvkehT13qZlYLLIewNiU5Yq4nBJKQbGXnp76kjdofFE0AG2EboDPfOziRGUfLUKW3xQaEoB1qLTEA1mXZOesYU3gyG6gFGJ2iSlcPXan/EO9j5RcyPpcPg4MGR/sir2bQMo/J4hqIitz3h4hy4zYCIXr3UBmiXhMMZHHEm1YjDe9srj"
#    password: "pfflgjzzkihpksck"
    default-encoding: UTF-8
    properties:
      mail:
        mime:
          charset: UTF
        smtp:
          ssl:
            trust: "smtp.gmail.com"
          writetimeout: 10000
          connectiontimeout: 10000
          timeout: 10000
          auth: true
          starttls:
            enable: true
            required: true
    subject: "Currency subscription"

logging:
  pattern:
    level: '%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]'

