spring:
  data:
    mongodb:
      authentication-database: admin
      username: test
      password: test
#      database: currency
      port: 27017
      host: currency-database
      database: test
      repositories:
        type: reactive
