spring:
  data:
    mongodb:
      uri:
      authentication-database: admin
      username: test
      password: test
      port: 27017
#      host: currency-database
      database: test
      repositories:
        type: reactive
currency:
  base-url: "https://api.apilayer.com/fixer/convert?"
  key: "p8vEn7uXb4MVTM9uwLnMstQozXxXC12A"
  fixedRate: 3600000
  from: "USD"
  to: "BYN"
  amount: 1.00