server:
  port: 0
spring:
  profiles:
    active:
      test
  application:
    name: currency
  eureka:
    client:
      service-url:
        defaultZone: ${EUREKA_URL}
    instance:
      instance-id: ${spring.application.name}:${random.uuid}
  data:
    mongodb:
      authentication-database: admin
      username: rootuser
      password: rootpass
      database: currency
      port: 27017
      host: currency-database

currency:
  base-url: "https://api.apilayer.com/fixer/convert?"
  key: "p8vEn7uXb4MVTM9uwLnMstQozXxXC12A"
  fixedRate: 3600000
  from: "USD"
  to: "BYN"
  amount: 1.00
