server:
  port: 0
spring:
  application:
    name: currency
  eureka:
    client:
      service-url:
        defaultZone: ${EUREKA_URL}
    instance:
      instance-id: ${spring.application.name}:${random.uuid}
  data:
    mongodb:
      authentication-database: admin
      username: rootuser
      password: "{cipher}AQCeEsYZiktT0zhrcY56YYZRZgUNAU91nxC9loPfV/B0F9xP34QTU64m1x/fCbAtdcSBwMVi/hntzuUWD6kEqUSzSYDjuKBApEDK0HY84UsYBAHeKDKzrTX7a+Y7MHJjrwEE78OCCxhWANEkkjV5bKEEYT1srgRJHxmx4eSApd2ekDYV8mcQlNtrKyp5foq1i67D7LSpp3NOcQL+F1DiEmgT06VtcgMI236/jEtukXK9E/0k10ry2L70TQEdugaS4W6LwL5q5qezIdMnTOP+i48tXHwsPIC/ebVv6NxnzjAbYebYChCnpwX4w+qRJIusLV2QH6E1hpJ1WCkENGIXeY8WuVs5l+Y1g8olidlmeysrz4Za7H/Csc+uKIQxwkbcyKQ="
#      password: rootpass
      database: currency
      port: 27017
      host: currency-database

currency:
  base-url: "https://api.apilayer.com/fixer/convert?"
  key: "{cipher}AQBEDlBsozbz1YCYoCn/zenaoAB5eHGO+96TI0YRmaHyUjkhhMEV5pRx3u8XDcXiYarEl8v45mmtc89n8zqVbuXO70gHOhXicPZRTxXffkg94e22iIJ84s5apOD72MXHSbtdro+ui6KQS2F5+6HaTl60TEnM1pr8R58UOWMixMEyiAVN3UeJJshQTTyFwFhzXbfI2zXes+36JTsLLEhTKJAvlQs2WnOkhTUlTfo+vuDK9xr9MLq8h1+tEO7SnqbenbxeLauBy+VW35CMv2KWV8CIJ8F4FCCo1SKl6Pea0oIlr3MG6KnhOu3oeDbgn5evkl8CwEtPwAUpL4+AosLAIBFar8pKjZSf4ssVXiXSfH5zDF7FsZEZGiM7WamC/P3WrvzqBMtA44Q84nWcU7Ox4HYNICVXILh9Pn0SAt6qveXRKg=="
#  key: "p8vEn7uXb4MVTM9uwLnMstQozXxXC12A"
  fixedRate: 3600000
  from: "USD"
  to: "BYN"
  amount: 1.00


