spring:
  r2dbc:
#    url: ${spring.r2dbc.url}
#    username: ${spring.r2dbc.username}
#    password: ${spring.r2dbc.password}
#    url: r2dbc:postgresql://users-database:5432/users
    url: r2dbc:tc:postgresql:///users-database?TC_IMAGE_TAG=14-alpine
    username: test
    password: test
