server:
  port: 0
spring:
  application:
    name: user-service
  eureka:
    client:
      service-url:
        defaultZone: ${EUREKA_URL}
    instance:
      instance-id: ${spring.application.name}:${random.uuid}
  r2dbc:
    url: r2dbc:postgresql://users-database:5432/users
    username: postgres
    password: "{cipher}AQAlF/+iPTkPDVRglAMSNleSN0/fkfmQRaqdpESUMpGQ0LSZLpxPCxOQ8duLayFRLozJWhJAPMpYE2zzrRk7rWMtOhpdbQACdwKMDtjT4+BvU7Fby2e8ahDFci5Sk2yFP1ZYr25m+mzt8PPlZzakp9VmihzpSm+B0w441Zfkv6NytzM2jx1riVgG4zBRv8m/UpqWgqoHqUKz7ctCG6IOjz6Q/hY7zO0Dv/7lWJvO7pMkVTNeFYtaszyymeYAVZOu0eY6sx1PLXj4m1bjHL9opEpgZoHW5EdzGEdzUyiUuZ6bPnu4bOxVQ05NtJQJWWMm3GQRaANTlvPqVokEBIV3k3lfdlxC8P4U1HoCB8MyGLpF6ze7oUeTY1QSOt4tXZDIWJc="
#    password: 123
  liquibase:
    change-log: db/changelog/db.changelog-master.yaml
    enabled: true

security:
  jwt:
    secret: "{cipher}AQBgZ0G5VHggRykzj80e0Hc1vm3sCwS4HDJPlUHzCOozV2qarV4tvNU6tlgc/vxSEp3CQYquH3mZiNuDOpgtmk0u0e3p7Jt75blmAYfoll9fq4t/Y6vC3mk30aFesUpYzjHrK7unXANF9wdxNZ1P/9ND0vuEezx34AnBY8F4e+NzcgCZmW3hEYaO0T/f+OCEH4X8ocCTh3kEm+Z74QwJ1vHTo04XyG1KPjb4lJCovM66XVirGJfTr1LILC5c8VG2pBXWhQM3/zWhiej4xNWCHCp61CVzMJf2AwkXyBBWVCEQcu7a0fOOEKEZ9TD7I8MdX5MXMIKJP/YUNHv5HGF62ZHPSzUOfUfDMcBL7jecGCt6HVIO+BoJzY+Q54MuwFMK9C7g5nY7LI0SG+XMXQyV6pyuPmBh5se4uIEorrsAnOqkurR4YvyfPkUuuqF5gpQbaUZmH5++ThZ5iwd4GbNowpJeqwSekk5rklOVXB3sFKBvdNCqvQYC5uCMlOw/e5xycorS1hsBDt88U2MjcpKP81aChwnrkBSjtUOHFoIvXDmMto2yrsZUOEVGgvHQGzz1eaFms8TJvuGQJPVmBVFYGHDMHFShmRFvfCubyRqnW0y2Yy5eNBH/zs5mJcv1Lf3mD11PQDHahy7kbKiYZ1MoSlP0uTb5pX3NTpOFI2jX+/EqnbM5obDuQliXewbX1gUyuttOsBoDuk1pZnQRFF9bHpdK"
#    secret: 2AW9UBKG7ZGLLJ5W25V097ZUCEZJDT7O7KOV284EUMWQD7G9UK8Q9RFNY15D9RIUKAXQS9JVOJ1Z81KTJAG76BVY8AICAS88ZAAUJGW6FXJID00OZBQTYKGKHXMFOPT07SVNN669GFXG801TNZQW1YO467LY4VWYP0I18661GA1V94ZHZKWJ3938DRFYN8HA7ZZ5KV10XABAXNA7L1SCWG6YX7NG60QROUHQL4MH4QAVX4UL4XGGVVHNPT6AODP7

logging:
  pattern:
    level: '%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]'