server:
  port: 8085
spring:
  application:
    name: user-service
  eureka:
    client:
      service-url:
        defaultZone: ${EUREKA_URL}
    instance:
      instance-id: ${spring.application.name}:${random.uuid}
  r2dbc:
    url: r2dbc:postgresql://postgres:5432/testdb
    username: postgres
    password: 123