server:
  port: 0
spring:
  application:
    name: user-service
  eureka:
    client:
      service-url:
        defaultZone: ${EUREKA_URL}
    instance:
      instance-id: ${spring.application.name}:${random.uuid}
  r2dbc:
    url: r2dbc:postgresql://users-database:5432/users
    username: postgres
    password: 123

security:
  jwt:
#    secret: 2F413F4428472B4B61645367566B5970337336763979244226452948404D6351
    secret: 2AW9UBKG7ZGLLJ5W25V097ZUCEZJDT7O7KOV284EUMWQD7G9UK8Q9RFNY15D9RIUKAXQS9JVOJ1Z81KTJAG76BVY8AICAS88ZAAUJGW6FXJID00OZBQTYKGKHXMFOPT07SVNN669GFXG801TNZQW1YO467LY4VWYP0I18661GA1V94ZHZKWJ3938DRFYN8HA7ZZ5KV10XABAXNA7L1SCWG6YX7NG60QROUHQL4MH4QAVX4UL4XGGVVHNPT6AODP7